# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

logo: images/LHLogo.png
title: Lighthouse Mindset
email: marberrym@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  The Lighthouse Mindset is a mentality I try to live my life by each day.
  Using the knowledge, wisdom and experiences I've accumulated over the
  years to share my light with others.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://matthew-marberry.com/LHM" # the base hostname & protocol for your site, e.g. http://example.com


#Sidebar Pages
defaults:
  - scope:
      path: category/coding.md
    values:
      menu: true
      order: 1
  - scope:
      path: category/projects.md
    values:
      menu: true
      order: 2
  - scope:
      path: category/lifestyle.md
    values:
      menu: true
      order: 3
  - scope:
      path: resume.md
    values:
      menu: true
      order: 4
  - scope:
      path: about.md
    values:
      menu: true
      order: 5

#Categories
collections:
  featured_categories:
    permalink:         /:name/
    output:            true
  featured_tags:
    permalink:         /tag-:name/
    output:            true


#twitter_username: jekyllrb
github_username:  marberrym
linkedin_username: in/matthew-marberry-aa13b326
facebook_username: jaydoeee
instagram_username: jaydoee



# Build settings
markdown: kramdown
theme: jekyll-theme-hydejack
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

#Sidebar Pages

